// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file enum.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file enum.proto.
 */
export const file_enum: GenFile = /*@__PURE__*/
  fileDesc("CgplbnVtLnByb3RvEghQcm90b2NvbCozCg1Sb29tU3RhdGVUeXBlEggKBFdBSVQQABILCgdQUkVQQVJFEAESCwoHSU5BR0FNRRACKkkKCk9iamVjdFR5cGUSCQoFVE9XRVIQABIKCgZQTEFZRVIQARILCgdNT05TVEVSEAISDgoKUFJPSkVDVElMRRADEgcKA0VOVhAEKjIKEU9CSkVDVF9TVEFURV9UWVBFEggKBElETEUQABIICgRNT1ZFEAESCQoFU0tJTEwQAio0CghDYXJkVHlwZRITCg9DQVJEX1RZUEVfVE9XRVIQABITCg9DQVJEX1RZUEVfU0tJTEwQAWIGcHJvdG8z");

/**
 * 변경 주의(클라 의존성)
 *
 * @generated from enum Protocol.RoomStateType
 */
export enum RoomStateType {
  /**
   * @generated from enum value: WAIT = 0;
   */
  WAIT = 0,

  /**
   * @generated from enum value: PREPARE = 1;
   */
  PREPARE = 1,

  /**
   * @generated from enum value: INAGAME = 2;
   */
  INAGAME = 2,
}

/**
 * Describes the enum Protocol.RoomStateType.
 */
export const RoomStateTypeSchema: GenEnum<RoomStateType> = /*@__PURE__*/
  enumDesc(file_enum, 0);

/**
 * @generated from enum Protocol.ObjectType
 */
export enum ObjectType {
  /**
   * @generated from enum value: TOWER = 0;
   */
  TOWER = 0,

  /**
   * @generated from enum value: PLAYER = 1;
   */
  PLAYER = 1,

  /**
   * @generated from enum value: MONSTER = 2;
   */
  MONSTER = 2,

  /**
   * @generated from enum value: PROJECTILE = 3;
   */
  PROJECTILE = 3,

  /**
   * @generated from enum value: ENV = 4;
   */
  ENV = 4,
}

/**
 * Describes the enum Protocol.ObjectType.
 */
export const ObjectTypeSchema: GenEnum<ObjectType> = /*@__PURE__*/
  enumDesc(file_enum, 1);

/**
 * @generated from enum Protocol.OBJECT_STATE_TYPE
 */
export enum OBJECT_STATE_TYPE {
  /**
   * @generated from enum value: IDLE = 0;
   */
  IDLE = 0,

  /**
   * @generated from enum value: MOVE = 1;
   */
  MOVE = 1,

  /**
   * @generated from enum value: SKILL = 2;
   */
  SKILL = 2,
}

/**
 * Describes the enum Protocol.OBJECT_STATE_TYPE.
 */
export const OBJECT_STATE_TYPESchema: GenEnum<OBJECT_STATE_TYPE> = /*@__PURE__*/
  enumDesc(file_enum, 2);

/**
 * @generated from enum Protocol.CardType
 */
export enum CardType {
  /**
   * @generated from enum value: CARD_TYPE_TOWER = 0;
   */
  TOWER = 0,

  /**
   * @generated from enum value: CARD_TYPE_SKILL = 1;
   */
  SKILL = 1,
}

/**
 * Describes the enum Protocol.CardType.
 */
export const CardTypeSchema: GenEnum<CardType> = /*@__PURE__*/
  enumDesc(file_enum, 3);

