// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file init.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file init.proto.
 */
export const file_init: GenFile = /*@__PURE__*/
  fileDesc("Cgppbml0LnByb3RvEghQcm90b2NvbCIcCghHMkxfSW5pdBIQCghzZXJ2ZXJJZBgBIAEoCSIcCghHMkJfSW5pdBIQCghzZXJ2ZXJJZBgBIAEoCSIZCghDMkdfSW5pdBINCgV0b2tlbhgBIAEoCWIGcHJvdG8z", [file_struct]);

/**
 * @generated from message Protocol.G2L_Init
 */
export type G2L_Init = Message<"Protocol.G2L_Init"> & {
  /**
   * @generated from field: string serverId = 1;
   */
  serverId: string;
};

/**
 * Describes the message Protocol.G2L_Init.
 * Use `create(G2L_InitSchema)` to create a new message.
 */
export const G2L_InitSchema: GenMessage<G2L_Init> = /*@__PURE__*/
  messageDesc(file_init, 0);

/**
 * @generated from message Protocol.G2B_Init
 */
export type G2B_Init = Message<"Protocol.G2B_Init"> & {
  /**
   * @generated from field: string serverId = 1;
   */
  serverId: string;
};

/**
 * Describes the message Protocol.G2B_Init.
 * Use `create(G2B_InitSchema)` to create a new message.
 */
export const G2B_InitSchema: GenMessage<G2B_Init> = /*@__PURE__*/
  messageDesc(file_init, 1);

/**
 * @generated from message Protocol.C2G_Init
 */
export type C2G_Init = Message<"Protocol.C2G_Init"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message Protocol.C2G_Init.
 * Use `create(C2G_InitSchema)` to create a new message.
 */
export const C2G_InitSchema: GenMessage<C2G_Init> = /*@__PURE__*/
  messageDesc(file_init, 2);

