// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file skill.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_enum } from "./enum_pb";
import type { CardData, SkillData } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file skill.proto.
 */
export const file_skill: GenFile = /*@__PURE__*/
  fileDesc("Cgtza2lsbC5wcm90bxIIUHJvdG9jb2wiWQoTQzJHX1VzZVNraWxsUmVxdWVzdBIiCgVza2lsbBgBIAEoCzITLlByb3RvY29sLlNraWxsRGF0YRIOCgZyb29tSWQYAiABKAUSDgoGY2FyZElkGAMgASgJImkKE0cyQl9Vc2VTa2lsbFJlcXVlc3QSIgoFc2tpbGwYASABKAsyEy5Qcm90b2NvbC5Ta2lsbERhdGESDgoGcm9vbUlkGAIgASgFEg4KBmNhcmRJZBgDIAEoCRIOCgZ1c2VySWQYBCABKAkiSQoUQjJHX1VzZVNraWxsUmVzcG9uc2USDgoGcm9vbUlkGAEgASgFEhEKCWlzU3VjY2VzcxgCIAEoCBIOCgZjYXJkSWQYAyABKAkiOQoURzJDX1VzZVNraWxsUmVzcG9uc2USEQoJaXNTdWNjZXNzGAEgASgIEg4KBmNhcmRJZBgCIAEoCSJfChhCMkdfVXNlU2tpbGxOb3RpZmljYXRpb24SDgoGcm9vbUlkGAEgASgFEg8KB293bmVySWQYAiABKAkSIgoFc2tpbGwYAyABKAsyEy5Qcm90b2NvbC5Ta2lsbERhdGEiTwoYRzJDX1VzZVNraWxsTm90aWZpY2F0aW9uEg8KB293bmVySWQYASABKAkSIgoFc2tpbGwYAiABKAsyEy5Qcm90b2NvbC5Ta2lsbERhdGEiUwoLQjJHX0FkZENhcmQSDgoGcm9vbUlkGAEgASgFEg4KBnVzZXJJZBgCIAEoCRIkCghjYXJkRGF0YRgDIAEoCzISLlByb3RvY29sLkNhcmREYXRhIjMKC0cyQ19BZGRDYXJkEiQKCGNhcmREYXRhGAEgASgLMhIuUHJvdG9jb2wuQ2FyZERhdGEiSAoQQjJHX0luaXRDYXJkRGF0YRIkCghjYXJkRGF0YRgBIAMoCzISLlByb3RvY29sLkNhcmREYXRhEg4KBnVzZXJJZBgCIAEoCSI4ChBHMkNfSW5pdENhcmREYXRhEiQKCGNhcmREYXRhGAEgAygLMhIuUHJvdG9jb2wuQ2FyZERhdGFiBnByb3RvMw", [file_enum, file_struct]);

/**
 * @generated from message Protocol.C2G_UseSkillRequest
 */
export type C2G_UseSkillRequest = Message<"Protocol.C2G_UseSkillRequest"> & {
  /**
   * @generated from field: Protocol.SkillData skill = 1;
   */
  skill?: SkillData;

  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;

  /**
   * @generated from field: string cardId = 3;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.C2G_UseSkillRequest.
 * Use `create(C2G_UseSkillRequestSchema)` to create a new message.
 */
export const C2G_UseSkillRequestSchema: GenMessage<C2G_UseSkillRequest> = /*@__PURE__*/
  messageDesc(file_skill, 0);

/**
 * @generated from message Protocol.G2B_UseSkillRequest
 */
export type G2B_UseSkillRequest = Message<"Protocol.G2B_UseSkillRequest"> & {
  /**
   * @generated from field: Protocol.SkillData skill = 1;
   */
  skill?: SkillData;

  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;

  /**
   * @generated from field: string cardId = 3;
   */
  cardId: string;

  /**
   * @generated from field: string userId = 4;
   */
  userId: string;
};

/**
 * Describes the message Protocol.G2B_UseSkillRequest.
 * Use `create(G2B_UseSkillRequestSchema)` to create a new message.
 */
export const G2B_UseSkillRequestSchema: GenMessage<G2B_UseSkillRequest> = /*@__PURE__*/
  messageDesc(file_skill, 1);

/**
 * @generated from message Protocol.B2G_UseSkillResponse
 */
export type B2G_UseSkillResponse = Message<"Protocol.B2G_UseSkillResponse"> & {
  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 1;
   */
  roomId: number;

  /**
   * @generated from field: bool isSuccess = 2;
   */
  isSuccess: boolean;

  /**
   * @generated from field: string cardId = 3;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.B2G_UseSkillResponse.
 * Use `create(B2G_UseSkillResponseSchema)` to create a new message.
 */
export const B2G_UseSkillResponseSchema: GenMessage<B2G_UseSkillResponse> = /*@__PURE__*/
  messageDesc(file_skill, 2);

/**
 * 스킬 카드 사용 응답
 *
 * @generated from message Protocol.G2C_UseSkillResponse
 */
export type G2C_UseSkillResponse = Message<"Protocol.G2C_UseSkillResponse"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;

  /**
   * 카드 사용 요청 -> 서버로부터 응답을 받으면: 패에서 카드 제거거거
   *
   * @generated from field: string cardId = 2;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.G2C_UseSkillResponse.
 * Use `create(G2C_UseSkillResponseSchema)` to create a new message.
 */
export const G2C_UseSkillResponseSchema: GenMessage<G2C_UseSkillResponse> = /*@__PURE__*/
  messageDesc(file_skill, 3);

/**
 * 스킬 카드 사용 알림
 *
 * @generated from message Protocol.B2G_UseSkillNotification
 */
export type B2G_UseSkillNotification = Message<"Protocol.B2G_UseSkillNotification"> & {
  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 1;
   */
  roomId: number;

  /**
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;

  /**
   * @generated from field: Protocol.SkillData skill = 3;
   */
  skill?: SkillData;
};

/**
 * Describes the message Protocol.B2G_UseSkillNotification.
 * Use `create(B2G_UseSkillNotificationSchema)` to create a new message.
 */
export const B2G_UseSkillNotificationSchema: GenMessage<B2G_UseSkillNotification> = /*@__PURE__*/
  messageDesc(file_skill, 4);

/**
 * @generated from message Protocol.G2C_UseSkillNotification
 */
export type G2C_UseSkillNotification = Message<"Protocol.G2C_UseSkillNotification"> & {
  /**
   * @generated from field: string ownerId = 1;
   */
  ownerId: string;

  /**
   * @generated from field: Protocol.SkillData skill = 2;
   */
  skill?: SkillData;
};

/**
 * Describes the message Protocol.G2C_UseSkillNotification.
 * Use `create(G2C_UseSkillNotificationSchema)` to create a new message.
 */
export const G2C_UseSkillNotificationSchema: GenMessage<G2C_UseSkillNotification> = /*@__PURE__*/
  messageDesc(file_skill, 5);

/**
 * 카드 추가 알림
 *
 * @generated from message Protocol.B2G_AddCard
 */
export type B2G_AddCard = Message<"Protocol.B2G_AddCard"> & {
  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 1;
   */
  roomId: number;

  /**
   * @generated from field: string userId = 2;
   */
  userId: string;

  /**
   * @generated from field: Protocol.CardData cardData = 3;
   */
  cardData?: CardData;
};

/**
 * Describes the message Protocol.B2G_AddCard.
 * Use `create(B2G_AddCardSchema)` to create a new message.
 */
export const B2G_AddCardSchema: GenMessage<B2G_AddCard> = /*@__PURE__*/
  messageDesc(file_skill, 6);

/**
 * 카드 추가 알림
 *
 * @generated from message Protocol.G2C_AddCard
 */
export type G2C_AddCard = Message<"Protocol.G2C_AddCard"> & {
  /**
   * @generated from field: Protocol.CardData cardData = 1;
   */
  cardData?: CardData;
};

/**
 * Describes the message Protocol.G2C_AddCard.
 * Use `create(G2C_AddCardSchema)` to create a new message.
 */
export const G2C_AddCardSchema: GenMessage<G2C_AddCard> = /*@__PURE__*/
  messageDesc(file_skill, 7);

/**
 * 초기 카드 데이터 알림
 *
 * @generated from message Protocol.B2G_InitCardData
 */
export type B2G_InitCardData = Message<"Protocol.B2G_InitCardData"> & {
  /**
   * @generated from field: repeated Protocol.CardData cardData = 1;
   */
  cardData: CardData[];

  /**
   * @generated from field: string userId = 2;
   */
  userId: string;
};

/**
 * Describes the message Protocol.B2G_InitCardData.
 * Use `create(B2G_InitCardDataSchema)` to create a new message.
 */
export const B2G_InitCardDataSchema: GenMessage<B2G_InitCardData> = /*@__PURE__*/
  messageDesc(file_skill, 8);

/**
 * @generated from message Protocol.G2C_InitCardData
 */
export type G2C_InitCardData = Message<"Protocol.G2C_InitCardData"> & {
  /**
   * @generated from field: repeated Protocol.CardData cardData = 1;
   */
  cardData: CardData[];
};

/**
 * Describes the message Protocol.G2C_InitCardData.
 * Use `create(G2C_InitCardDataSchema)` to create a new message.
 */
export const G2C_InitCardDataSchema: GenMessage<G2C_InitCardData> = /*@__PURE__*/
  messageDesc(file_skill, 9);

