// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file character.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PosInfo } from "./struct_pb";
import { file_struct } from "./struct_pb";
import { file_enum } from "./enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file character.proto.
 */
export const file_character: GenFile = /*@__PURE__*/
  fileDesc("Cg9jaGFyYWN0ZXIucHJvdG8SCFByb3RvY29sIlUKH0MyR19QbGF5ZXJQb3NpdGlvblVwZGF0ZVJlcXVlc3QSIgoHcG9zSW5mbxgBIAEoCzIRLlByb3RvY29sLlBvc0luZm8SDgoGcm9vbUlkGAIgASgFIlUKH0cyQl9QbGF5ZXJQb3NpdGlvblVwZGF0ZVJlcXVlc3QSIgoHcG9zSW5mbxgBIAEoCzIRLlByb3RvY29sLlBvc0luZm8SDgoGcm9vbUlkGAIgASgFIloKJEIyR19QbGF5ZXJQb3NpdGlvblVwZGF0ZU5vdGlmaWNhdGlvbhIiCgdwb3NJbmZvGAEgASgLMhEuUHJvdG9jb2wuUG9zSW5mbxIOCgZyb29tSWQYAiABKAUiSgokRzJDX1BsYXllclBvc2l0aW9uVXBkYXRlTm90aWZpY2F0aW9uEiIKB3Bvc0luZm8YASABKAsyES5Qcm90b2NvbC5Qb3NJbmZvIjQKEkMyQl9Vc2VDYXJkUmVxdWVzdBIOCgZyb29tSWQYASABKAUSDgoGY2FyZElkGAIgASgJYgZwcm90bzM", [file_struct, file_enum]);

/**
 * 캐릭터 위치 동기화
 *
 * @generated from message Protocol.C2G_PlayerPositionUpdateRequest
 */
export type C2G_PlayerPositionUpdateRequest = Message<"Protocol.C2G_PlayerPositionUpdateRequest"> & {
  /**
   * @generated from field: Protocol.PosInfo posInfo = 1;
   */
  posInfo?: PosInfo;

  /**
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.C2G_PlayerPositionUpdateRequest.
 * Use `create(C2G_PlayerPositionUpdateRequestSchema)` to create a new message.
 */
export const C2G_PlayerPositionUpdateRequestSchema: GenMessage<C2G_PlayerPositionUpdateRequest> = /*@__PURE__*/
  messageDesc(file_character, 0);

/**
 * @generated from message Protocol.G2B_PlayerPositionUpdateRequest
 */
export type G2B_PlayerPositionUpdateRequest = Message<"Protocol.G2B_PlayerPositionUpdateRequest"> & {
  /**
   * @generated from field: Protocol.PosInfo posInfo = 1;
   */
  posInfo?: PosInfo;

  /**
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.G2B_PlayerPositionUpdateRequest.
 * Use `create(G2B_PlayerPositionUpdateRequestSchema)` to create a new message.
 */
export const G2B_PlayerPositionUpdateRequestSchema: GenMessage<G2B_PlayerPositionUpdateRequest> = /*@__PURE__*/
  messageDesc(file_character, 1);

/**
 * 캐릭터 위치 동기화 알림
 *
 * @generated from message Protocol.B2G_PlayerPositionUpdateNotification
 */
export type B2G_PlayerPositionUpdateNotification = Message<"Protocol.B2G_PlayerPositionUpdateNotification"> & {
  /**
   * @generated from field: Protocol.PosInfo posInfo = 1;
   */
  posInfo?: PosInfo;

  /**
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.B2G_PlayerPositionUpdateNotification.
 * Use `create(B2G_PlayerPositionUpdateNotificationSchema)` to create a new message.
 */
export const B2G_PlayerPositionUpdateNotificationSchema: GenMessage<B2G_PlayerPositionUpdateNotification> = /*@__PURE__*/
  messageDesc(file_character, 2);

/**
 * 캐릭터 위치 동기화 알림
 *
 * @generated from message Protocol.G2C_PlayerPositionUpdateNotification
 */
export type G2C_PlayerPositionUpdateNotification = Message<"Protocol.G2C_PlayerPositionUpdateNotification"> & {
  /**
   * @generated from field: Protocol.PosInfo posInfo = 1;
   */
  posInfo?: PosInfo;
};

/**
 * Describes the message Protocol.G2C_PlayerPositionUpdateNotification.
 * Use `create(G2C_PlayerPositionUpdateNotificationSchema)` to create a new message.
 */
export const G2C_PlayerPositionUpdateNotificationSchema: GenMessage<G2C_PlayerPositionUpdateNotification> = /*@__PURE__*/
  messageDesc(file_character, 3);

/**
 * 카드 사용
 *
 * @generated from message Protocol.C2B_UseCardRequest
 */
export type C2B_UseCardRequest = Message<"Protocol.C2B_UseCardRequest"> & {
  /**
   * @generated from field: int32 roomId = 1;
   */
  roomId: number;

  /**
   * @generated from field: string cardId = 2;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.C2B_UseCardRequest.
 * Use `create(C2B_UseCardRequestSchema)` to create a new message.
 */
export const C2B_UseCardRequestSchema: GenMessage<C2B_UseCardRequest> = /*@__PURE__*/
  messageDesc(file_character, 4);

