// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file monster.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PosInfo } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file monster.proto.
 */
export const file_monster: GenFile = /*@__PURE__*/
  fileDesc("Cg1tb25zdGVyLnByb3RvEghQcm90b2NvbCJUChxCMkNfU3Bhd25Nb25zdGVyTm90aWZpY2F0aW9uEiIKB3Bvc0luZm8YASABKAsyES5Qcm90b2NvbC5Qb3NJbmZvEhAKCHByZWZhYklkGAIgASgJIkAKHEIyQ19Nb25zdGVyRGVhdGhOb3RpZmljYXRpb24SEQoJbW9uc3RlcklkGAEgASgJEg0KBXNjb3JlGAIgASgFIksKJUIyQ19Nb25zdGVyUG9zaXRpb25VcGRhdGVOb3RpZmljYXRpb24SIgoHcG9zSW5mbxgBIAEoCzIRLlByb3RvY29sLlBvc0luZm8iZAoiQjJDX01vbnN0ZXJBdHRhY2tUb3dlck5vdGlmaWNhdGlvbhIRCgltb25zdGVySWQYASABKAkSEAoIdGFyZ2V0SWQYAiABKAkSCgoCaHAYAyABKAUSDQoFbWF4SHAYBCABKAUiTAohQjJDX01vbnN0ZXJBdHRhY2tCYXNlTm90aWZpY2F0aW9uEhEKCW1vbnN0ZXJJZBgBIAEoCRIUCgxhdHRhY2tEYW1hZ2UYAiABKAUiUwojQjJDX01vbnN0ZXJIZWFsdGhVcGRhdGVOb3RpZmljYXRpb24SEQoJbW9uc3RlcklkGAEgASgJEgoKAmhwGAIgASgFEg0KBW1heEhwGAMgASgFIj4KG0IyQ19Nb25zdGVyQnVmZk5vdGlmaWNhdGlvbhIQCghidWZmVHlwZRgBIAEoCRINCgVzdGF0ZRgCIAEoCGIGcHJvdG8z", [file_struct]);

/**
 * 몬스터 생성 알림
 *
 * @generated from message Protocol.B2C_SpawnMonsterNotification
 */
export type B2C_SpawnMonsterNotification = Message<"Protocol.B2C_SpawnMonsterNotification"> & {
  /**
   * @generated from field: Protocol.PosInfo posInfo = 1;
   */
  posInfo?: PosInfo;

  /**
   * @generated from field: string prefabId = 2;
   */
  prefabId: string;
};

/**
 * Describes the message Protocol.B2C_SpawnMonsterNotification.
 * Use `create(B2C_SpawnMonsterNotificationSchema)` to create a new message.
 */
export const B2C_SpawnMonsterNotificationSchema: GenMessage<B2C_SpawnMonsterNotification> = /*@__PURE__*/
  messageDesc(file_monster, 0);

/**
 * 몬스터 사망 알림
 *
 * @generated from message Protocol.B2C_MonsterDeathNotification
 */
export type B2C_MonsterDeathNotification = Message<"Protocol.B2C_MonsterDeathNotification"> & {
  /**
   * @generated from field: string monsterId = 1;
   */
  monsterId: string;

  /**
   * @generated from field: int32 score = 2;
   */
  score: number;
};

/**
 * Describes the message Protocol.B2C_MonsterDeathNotification.
 * Use `create(B2C_MonsterDeathNotificationSchema)` to create a new message.
 */
export const B2C_MonsterDeathNotificationSchema: GenMessage<B2C_MonsterDeathNotification> = /*@__PURE__*/
  messageDesc(file_monster, 1);

/**
 * 몬스터 위치 동기화
 *
 * @generated from message Protocol.B2C_MonsterPositionUpdateNotification
 */
export type B2C_MonsterPositionUpdateNotification = Message<"Protocol.B2C_MonsterPositionUpdateNotification"> & {
  /**
   * @generated from field: Protocol.PosInfo posInfo = 1;
   */
  posInfo?: PosInfo;
};

/**
 * Describes the message Protocol.B2C_MonsterPositionUpdateNotification.
 * Use `create(B2C_MonsterPositionUpdateNotificationSchema)` to create a new message.
 */
export const B2C_MonsterPositionUpdateNotificationSchema: GenMessage<B2C_MonsterPositionUpdateNotification> = /*@__PURE__*/
  messageDesc(file_monster, 2);

/**
 * 몬스터 -> 타워 공격 알림
 *
 * @generated from message Protocol.B2C_MonsterAttackTowerNotification
 */
export type B2C_MonsterAttackTowerNotification = Message<"Protocol.B2C_MonsterAttackTowerNotification"> & {
  /**
   * @generated from field: string monsterId = 1;
   */
  monsterId: string;

  /**
   * @generated from field: string targetId = 2;
   */
  targetId: string;

  /**
   * @generated from field: int32 hp = 3;
   */
  hp: number;

  /**
   * @generated from field: int32 maxHp = 4;
   */
  maxHp: number;
};

/**
 * Describes the message Protocol.B2C_MonsterAttackTowerNotification.
 * Use `create(B2C_MonsterAttackTowerNotificationSchema)` to create a new message.
 */
export const B2C_MonsterAttackTowerNotificationSchema: GenMessage<B2C_MonsterAttackTowerNotification> = /*@__PURE__*/
  messageDesc(file_monster, 3);

/**
 * 몬스터 -> 베이스 공격 알림
 *
 * @generated from message Protocol.B2C_MonsterAttackBaseNotification
 */
export type B2C_MonsterAttackBaseNotification = Message<"Protocol.B2C_MonsterAttackBaseNotification"> & {
  /**
   * @generated from field: string monsterId = 1;
   */
  monsterId: string;

  /**
   * @generated from field: int32 attackDamage = 2;
   */
  attackDamage: number;
};

/**
 * Describes the message Protocol.B2C_MonsterAttackBaseNotification.
 * Use `create(B2C_MonsterAttackBaseNotificationSchema)` to create a new message.
 */
export const B2C_MonsterAttackBaseNotificationSchema: GenMessage<B2C_MonsterAttackBaseNotification> = /*@__PURE__*/
  messageDesc(file_monster, 4);

/**
 * 몬스터 체력 업데이트
 *
 * @generated from message Protocol.B2C_MonsterHealthUpdateNotification
 */
export type B2C_MonsterHealthUpdateNotification = Message<"Protocol.B2C_MonsterHealthUpdateNotification"> & {
  /**
   * @generated from field: string monsterId = 1;
   */
  monsterId: string;

  /**
   * @generated from field: int32 hp = 2;
   */
  hp: number;

  /**
   * @generated from field: int32 maxHp = 3;
   */
  maxHp: number;
};

/**
 * Describes the message Protocol.B2C_MonsterHealthUpdateNotification.
 * Use `create(B2C_MonsterHealthUpdateNotificationSchema)` to create a new message.
 */
export const B2C_MonsterHealthUpdateNotificationSchema: GenMessage<B2C_MonsterHealthUpdateNotification> = /*@__PURE__*/
  messageDesc(file_monster, 5);

/**
 * @generated from message Protocol.B2C_MonsterBuffNotification
 */
export type B2C_MonsterBuffNotification = Message<"Protocol.B2C_MonsterBuffNotification"> & {
  /**
   * @generated from field: string buffType = 1;
   */
  buffType: string;

  /**
   * @generated from field: bool state = 2;
   */
  state: boolean;
};

/**
 * Describes the message Protocol.B2C_MonsterBuffNotification.
 * Use `create(B2C_MonsterBuffNotificationSchema)` to create a new message.
 */
export const B2C_MonsterBuffNotificationSchema: GenMessage<B2C_MonsterBuffNotification> = /*@__PURE__*/
  messageDesc(file_monster, 6);

