// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file struct.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_enum } from "./enum_pb";

/**
 * Describes the file struct.proto.
 */
export const file_struct = /*@__PURE__*/
  fileDesc("CgxzdHJ1Y3QucHJvdG8SCFByb3RvY29sIiUKCEJhc2VEYXRhEgoKAmhwGAEgASgFEg0KBW1heEhwGAIgASgFIm0KC01vbnN0ZXJEYXRhEhEKCW1vbnN0ZXJJZBgBIAEoBRIVCg1tb25zdGVyTnVtYmVyGAIgASgFEg0KBWxldmVsGAMgASgFEiUKCm1vbnN0ZXJQb3MYBCABKAsyES5Qcm90b2NvbC5Qb3NJbmZvIjYKCFVzZXJEYXRhEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEAoIcHJlZmFiSWQYAyABKAkilAEKCFJvb21EYXRhEgoKAmlkGAEgASgFEg8KB293bmVySWQYAiABKAkSDAoEbmFtZRgDIAEoCRISCgptYXhVc2VyTnVtGAQgASgFEiYKBXN0YXRlGAUgASgOMhcuUHJvdG9jb2wuUm9vbVN0YXRlVHlwZRIhCgV1c2VycxgGIAMoCzISLlByb3RvY29sLlVzZXJEYXRhIi0KB1Bvc0luZm8SDAoEdXVpZBgBIAEoCRIJCgF4GAIgASgCEgkKAXkYAyABKAIiWQoOR2FtZVBsYXllckRhdGESIwoIcG9zaXRpb24YASABKAsyES5Qcm90b2NvbC5Qb3NJbmZvEhAKCG5pY2tuYW1lGAIgASgJEhAKCHByZWZhYklkGAMgASgJIjIKCUVycm9yRGF0YRIUCgxyZXNwb25zZUNvZGUYASABKAUSDwoHbWVzc2FnZRgCIAEoCSJTCglUb3dlckRhdGESDwoHdG93ZXJJZBgBIAEoCRIQCghwcmVmYWJJZBgCIAEoCRIjCgh0b3dlclBvcxgDIAEoCzIRLlByb3RvY29sLlBvc0luZm8iQgoJU2tpbGxEYXRhEhAKCHByZWZhYklkGAEgASgJEiMKCHNraWxsUG9zGAIgASgLMhEuUHJvdG9jb2wuUG9zSW5mbyIsCghDYXJkRGF0YRIOCgZjYXJkSWQYASABKAkSEAoIcHJlZmFiSWQYAiABKAkiSgoTTW9uc3RlckhlYWx0aFVwZGF0ZRIRCgltb25zdGVySWQYASABKAkSEQoJY3VycmVudEhwGAIgASgFEg0KBW1heEhwGAMgASgFYgZwcm90bzM", [file_enum]);

/**
 * Describes the message Protocol.BaseData.
 * Use `create(BaseDataSchema)` to create a new message.
 */
export const BaseDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 0);

/**
 * Describes the message Protocol.MonsterData.
 * Use `create(MonsterDataSchema)` to create a new message.
 */
export const MonsterDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 1);

/**
 * Describes the message Protocol.UserData.
 * Use `create(UserDataSchema)` to create a new message.
 */
export const UserDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 2);

/**
 * Describes the message Protocol.RoomData.
 * Use `create(RoomDataSchema)` to create a new message.
 */
export const RoomDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 3);

/**
 * Describes the message Protocol.PosInfo.
 * Use `create(PosInfoSchema)` to create a new message.
 */
export const PosInfoSchema = /*@__PURE__*/
  messageDesc(file_struct, 4);

/**
 * Describes the message Protocol.GamePlayerData.
 * Use `create(GamePlayerDataSchema)` to create a new message.
 */
export const GamePlayerDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 5);

/**
 * Describes the message Protocol.ErrorData.
 * Use `create(ErrorDataSchema)` to create a new message.
 */
export const ErrorDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 6);

/**
 * Describes the message Protocol.TowerData.
 * Use `create(TowerDataSchema)` to create a new message.
 */
export const TowerDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 7);

/**
 * Describes the message Protocol.SkillData.
 * Use `create(SkillDataSchema)` to create a new message.
 */
export const SkillDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 8);

/**
 * Describes the message Protocol.CardData.
 * Use `create(CardDataSchema)` to create a new message.
 */
export const CardDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 9);

/**
 * Describes the message Protocol.MonsterHealthUpdate.
 * Use `create(MonsterHealthUpdateSchema)` to create a new message.
 */
export const MonsterHealthUpdateSchema = /*@__PURE__*/
  messageDesc(file_struct, 10);

