// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file tower.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PosInfo, TowerData } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tower.proto.
 */
export const file_tower: GenFile = /*@__PURE__*/
  fileDesc("Cgt0b3dlci5wcm90bxIIUHJvdG9jb2wibAoVQzJCX1Rvd2VyQnVpbGRSZXF1ZXN0EiIKBXRvd2VyGAEgASgLMhMuUHJvdG9jb2wuVG93ZXJEYXRhEg8KB293bmVySWQYAiABKAkSDgoGcm9vbUlkGAMgASgFEg4KBmNhcmRJZBgEIAEoCSIrChZCMkNfVG93ZXJCdWlsZFJlc3BvbnNlEhEKCWlzU3VjY2VzcxgBIAEoCCJRChpCMkNfVG93ZXJCdWlsZE5vdGlmaWNhdGlvbhIiCgV0b3dlchgBIAEoCzITLlByb3RvY29sLlRvd2VyRGF0YRIPCgdvd25lcklkGAIgASgJInAKIkIyQ19Ub3dlckF0dGFja01vbnN0ZXJOb3RpZmljYXRpb24SDwoHdG93ZXJJZBgBIAEoCRIlCgptb25zdGVyUG9zGAIgASgLMhEuUHJvdG9jb2wuUG9zSW5mbxISCgp0cmF2ZWxUaW1lGAMgASgCIkIKHEIyQ19Ub3dlckRlc3Ryb3lOb3RpZmljYXRpb24SEQoJaXNTdWNjZXNzGAEgASgIEg8KB3Rvd2VySWQYAiABKAkiMgobQjJDX0Jhc2VEZXN0cm95Tm90aWZpY2F0aW9uEhMKC2lzRGVzdHJvaWVkGAEgASgIIk8KIUIyQ19Ub3dlckhlYWx0aFVwZGF0ZU5vdGlmaWNhdGlvbhIPCgd0b3dlcklkGAEgASgJEgoKAmhwGAIgASgFEg0KBW1heEhwGAMgASgFIlAKGUIyQ19Ub3dlckJ1ZmZOb3RpZmljYXRpb24SDwoHdG93ZXJJZBgBIAMoCRIQCghidWZmVHlwZRgCIAEoCRIQCghpc0J1ZmZlZBgDIAEoCGIGcHJvdG8z", [file_struct]);

/**
 * 타워 생성 요청
 *
 * @generated from message Protocol.C2B_TowerBuildRequest
 */
export type C2B_TowerBuildRequest = Message<"Protocol.C2B_TowerBuildRequest"> & {
  /**
   * 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 유저 ID
   *
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;

  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 3;
   */
  roomId: number;

  /**
   * @generated from field: string cardId = 4;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.C2B_TowerBuildRequest.
 * Use `create(C2B_TowerBuildRequestSchema)` to create a new message.
 */
export const C2B_TowerBuildRequestSchema: GenMessage<C2B_TowerBuildRequest> = /*@__PURE__*/
  messageDesc(file_tower, 0);

/**
 * 타워 생성 응답
 *
 * @generated from message Protocol.B2C_TowerBuildResponse
 */
export type B2C_TowerBuildResponse = Message<"Protocol.B2C_TowerBuildResponse"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;
};

/**
 * Describes the message Protocol.B2C_TowerBuildResponse.
 * Use `create(B2C_TowerBuildResponseSchema)` to create a new message.
 */
export const B2C_TowerBuildResponseSchema: GenMessage<B2C_TowerBuildResponse> = /*@__PURE__*/
  messageDesc(file_tower, 1);

/**
 * 타워 생성 알림
 *
 * @generated from message Protocol.B2C_TowerBuildNotification
 */
export type B2C_TowerBuildNotification = Message<"Protocol.B2C_TowerBuildNotification"> & {
  /**
   * 생성된 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 타워 생성자 ID
   *
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;
};

/**
 * Describes the message Protocol.B2C_TowerBuildNotification.
 * Use `create(B2C_TowerBuildNotificationSchema)` to create a new message.
 */
export const B2C_TowerBuildNotificationSchema: GenMessage<B2C_TowerBuildNotification> = /*@__PURE__*/
  messageDesc(file_tower, 2);

/**
 * 타워 -> 몬스터 공격 알림
 *
 * @generated from message Protocol.B2C_TowerAttackMonsterNotification
 */
export type B2C_TowerAttackMonsterNotification = Message<"Protocol.B2C_TowerAttackMonsterNotification"> & {
  /**
   * @generated from field: string towerId = 1;
   */
  towerId: string;

  /**
   * @generated from field: Protocol.PosInfo monsterPos = 2;
   */
  monsterPos?: PosInfo;

  /**
   * @generated from field: float travelTime = 3;
   */
  travelTime: number;
};

/**
 * Describes the message Protocol.B2C_TowerAttackMonsterNotification.
 * Use `create(B2C_TowerAttackMonsterNotificationSchema)` to create a new message.
 */
export const B2C_TowerAttackMonsterNotificationSchema: GenMessage<B2C_TowerAttackMonsterNotification> = /*@__PURE__*/
  messageDesc(file_tower, 3);

/**
 * 타워 파괴 알림
 *
 * @generated from message Protocol.B2C_TowerDestroyNotification
 */
export type B2C_TowerDestroyNotification = Message<"Protocol.B2C_TowerDestroyNotification"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;

  /**
   * @generated from field: string towerId = 2;
   */
  towerId: string;
};

/**
 * Describes the message Protocol.B2C_TowerDestroyNotification.
 * Use `create(B2C_TowerDestroyNotificationSchema)` to create a new message.
 */
export const B2C_TowerDestroyNotificationSchema: GenMessage<B2C_TowerDestroyNotification> = /*@__PURE__*/
  messageDesc(file_tower, 4);

/**
 * 베이스 파괴 알림
 *
 * @generated from message Protocol.B2C_BaseDestroyNotification
 */
export type B2C_BaseDestroyNotification = Message<"Protocol.B2C_BaseDestroyNotification"> & {
  /**
   * @generated from field: bool isDestroied = 1;
   */
  isDestroied: boolean;
};

/**
 * Describes the message Protocol.B2C_BaseDestroyNotification.
 * Use `create(B2C_BaseDestroyNotificationSchema)` to create a new message.
 */
export const B2C_BaseDestroyNotificationSchema: GenMessage<B2C_BaseDestroyNotification> = /*@__PURE__*/
  messageDesc(file_tower, 5);

/**
 * 타워 체력 업데이트 알림
 *
 * @generated from message Protocol.B2C_TowerHealthUpdateNotification
 */
export type B2C_TowerHealthUpdateNotification = Message<"Protocol.B2C_TowerHealthUpdateNotification"> & {
  /**
   * @generated from field: string towerId = 1;
   */
  towerId: string;

  /**
   * @generated from field: int32 hp = 2;
   */
  hp: number;

  /**
   * @generated from field: int32 maxHp = 3;
   */
  maxHp: number;
};

/**
 * Describes the message Protocol.B2C_TowerHealthUpdateNotification.
 * Use `create(B2C_TowerHealthUpdateNotificationSchema)` to create a new message.
 */
export const B2C_TowerHealthUpdateNotificationSchema: GenMessage<B2C_TowerHealthUpdateNotification> = /*@__PURE__*/
  messageDesc(file_tower, 6);

/**
 * 타워 버프 상태 알림
 *
 * @generated from message Protocol.B2C_TowerBuffNotification
 */
export type B2C_TowerBuffNotification = Message<"Protocol.B2C_TowerBuffNotification"> & {
  /**
   * 버프 받은/해제된 타워 ID
   *
   * @generated from field: repeated string towerId = 1;
   */
  towerId: string[];

  /**
   * "atkBuff", "asBuff"
   *
   * @generated from field: string buffType = 2;
   */
  buffType: string;

  /**
   * true: 버프 적용, false: 버프 해제
   *
   * @generated from field: bool isBuffed = 3;
   */
  isBuffed: boolean;
};

/**
 * Describes the message Protocol.B2C_TowerBuffNotification.
 * Use `create(B2C_TowerBuffNotificationSchema)` to create a new message.
 */
export const B2C_TowerBuffNotificationSchema: GenMessage<B2C_TowerBuffNotification> = /*@__PURE__*/
  messageDesc(file_tower, 7);

