// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file tower.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_struct } from "./struct_pb.js";

/**
 * Describes the file tower.proto.
 */
export const file_tower = /*@__PURE__*/
  fileDesc("Cgt0b3dlci5wcm90bxIIUHJvdG9jb2wibAoVQzJCX1Rvd2VyQnVpbGRSZXF1ZXN0EiIKBXRvd2VyGAEgASgLMhMuUHJvdG9jb2wuVG93ZXJEYXRhEg8KB293bmVySWQYAiABKAkSDgoGcm9vbUlkGAMgASgFEg4KBmNhcmRJZBgEIAEoCSIrChZCMkNfVG93ZXJCdWlsZFJlc3BvbnNlEhEKCWlzU3VjY2VzcxgBIAEoCCJRChpCMkNfVG93ZXJCdWlsZE5vdGlmaWNhdGlvbhIiCgV0b3dlchgBIAEoCzITLlByb3RvY29sLlRvd2VyRGF0YRIPCgdvd25lcklkGAIgASgJInAKIkIyQ19Ub3dlckF0dGFja01vbnN0ZXJOb3RpZmljYXRpb24SDwoHdG93ZXJJZBgBIAEoCRIlCgptb25zdGVyUG9zGAIgASgLMhEuUHJvdG9jb2wuUG9zSW5mbxISCgp0cmF2ZWxUaW1lGAMgASgCIkIKHEIyQ19Ub3dlckRlc3Ryb3lOb3RpZmljYXRpb24SEQoJaXNTdWNjZXNzGAEgASgIEg8KB3Rvd2VySWQYAiABKAkiMgobQjJDX0Jhc2VEZXN0cm95Tm90aWZpY2F0aW9uEhMKC2lzRGVzdHJvaWVkGAEgASgIYgZwcm90bzM", [file_struct]);

/**
 * Describes the message Protocol.C2B_TowerBuildRequest.
 * Use `create(C2B_TowerBuildRequestSchema)` to create a new message.
 */
export const C2B_TowerBuildRequestSchema = /*@__PURE__*/
  messageDesc(file_tower, 0);

/**
 * Describes the message Protocol.B2C_TowerBuildResponse.
 * Use `create(B2C_TowerBuildResponseSchema)` to create a new message.
 */
export const B2C_TowerBuildResponseSchema = /*@__PURE__*/
  messageDesc(file_tower, 1);

/**
 * Describes the message Protocol.B2C_TowerBuildNotification.
 * Use `create(B2C_TowerBuildNotificationSchema)` to create a new message.
 */
export const B2C_TowerBuildNotificationSchema = /*@__PURE__*/
  messageDesc(file_tower, 2);

/**
 * Describes the message Protocol.B2C_TowerAttackMonsterNotification.
 * Use `create(B2C_TowerAttackMonsterNotificationSchema)` to create a new message.
 */
export const B2C_TowerAttackMonsterNotificationSchema = /*@__PURE__*/
  messageDesc(file_tower, 3);

/**
 * Describes the message Protocol.B2C_TowerDestroyNotification.
 * Use `create(B2C_TowerDestroyNotificationSchema)` to create a new message.
 */
export const B2C_TowerDestroyNotificationSchema = /*@__PURE__*/
  messageDesc(file_tower, 4);

/**
 * Describes the message Protocol.B2C_BaseDestroyNotification.
 * Use `create(B2C_BaseDestroyNotificationSchema)` to create a new message.
 */
export const B2C_BaseDestroyNotificationSchema = /*@__PURE__*/
  messageDesc(file_tower, 5);

