// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file character.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_struct } from "./struct_pb";
import { file_enum } from "./enum_pb";

/**
 * Describes the file character.proto.
 */
export const file_character = /*@__PURE__*/
  fileDesc("Cg9jaGFyYWN0ZXIucHJvdG8SCFByb3RvY29sIlUKH0MyQl9QbGF5ZXJQb3NpdGlvblVwZGF0ZVJlcXVlc3QSIgoHcG9zSW5mbxgBIAEoCzIRLlByb3RvY29sLlBvc0luZm8SDgoGcm9vbUlkGAIgASgFIkoKJEIyQ19QbGF5ZXJQb3NpdGlvblVwZGF0ZU5vdGlmaWNhdGlvbhIiCgdwb3NJbmZvGAEgASgLMhEuUHJvdG9jb2wuUG9zSW5mbyI6ChJDMkJfVXNlQ2FyZFJlcXVlc3QSJAoIY2FyZFR5cGUYASABKA4yEi5Qcm90b2NvbC5DYXJkVHlwZSIsChdCMkNfVXNlQ2FyZE5vdGlmaWNhdGlvbhIRCglpc1N1Y2Nlc3MYASABKAhiBnByb3RvMw", [file_struct, file_enum]);

/**
 * Describes the message Protocol.C2B_PlayerPositionUpdateRequest.
 * Use `create(C2B_PlayerPositionUpdateRequestSchema)` to create a new message.
 */
export const C2B_PlayerPositionUpdateRequestSchema = /*@__PURE__*/
  messageDesc(file_character, 0);

/**
 * Describes the message Protocol.B2C_PlayerPositionUpdateNotification.
 * Use `create(B2C_PlayerPositionUpdateNotificationSchema)` to create a new message.
 */
export const B2C_PlayerPositionUpdateNotificationSchema = /*@__PURE__*/
  messageDesc(file_character, 1);

/**
 * Describes the message Protocol.C2B_UseCardRequest.
 * Use `create(C2B_UseCardRequestSchema)` to create a new message.
 */
export const C2B_UseCardRequestSchema = /*@__PURE__*/
  messageDesc(file_character, 2);

/**
 * Describes the message Protocol.B2C_UseCardNotification.
 * Use `create(B2C_UseCardNotificationSchema)` to create a new message.
 */
export const B2C_UseCardNotificationSchema = /*@__PURE__*/
  messageDesc(file_character, 3);

