// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file init.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_struct } from "./struct_pb";

/**
 * Describes the file init.proto.
 */
export const file_init = /*@__PURE__*/
  fileDesc("Cgppbml0LnByb3RvEghQcm90b2NvbCIdCghMMkNfSW5pdBIRCglpc1N1Y2Nlc3MYASABKAgiLAoIQzJMX0luaXQSDgoGdXNlcklkGAEgASgJEhAKCG5pY2tuYW1lGAIgASgJIkgKCEMyQl9Jbml0EiwKCnBsYXllckRhdGEYASABKAsyGC5Qcm90b2NvbC5HYW1lUGxheWVyRGF0YRIOCgZyb29tSWQYAiABKAUiHAoIQjJMX0luaXQSEAoIc2VydmVySWQYASABKAliBnByb3RvMw", [file_struct]);

/**
 * Describes the message Protocol.L2C_Init.
 * Use `create(L2C_InitSchema)` to create a new message.
 */
export const L2C_InitSchema = /*@__PURE__*/
  messageDesc(file_init, 0);

/**
 * Describes the message Protocol.C2L_Init.
 * Use `create(C2L_InitSchema)` to create a new message.
 */
export const C2L_InitSchema = /*@__PURE__*/
  messageDesc(file_init, 1);

/**
 * Describes the message Protocol.C2B_Init.
 * Use `create(C2B_InitSchema)` to create a new message.
 */
export const C2B_InitSchema = /*@__PURE__*/
  messageDesc(file_init, 2);

/**
 * Describes the message Protocol.B2L_Init.
 * Use `create(B2L_InitSchema)` to create a new message.
 */
export const B2L_InitSchema = /*@__PURE__*/
  messageDesc(file_init, 3);

