// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file skill.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_enum } from "./enum_pb";
import type { CardData, SkillData } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file skill.proto.
 */
export const file_skill: GenFile = /*@__PURE__*/
  fileDesc("Cgtza2lsbC5wcm90bxIIUHJvdG9jb2wiVgoQQzJCX1NraWxsUmVxdWVzdBIiCgVza2lsbBgBIAEoCzITLlByb3RvY29sLlNraWxsRGF0YRIOCgZyb29tSWQYAiABKAUSDgoGY2FyZElkGAMgASgJIjYKEUIyQ19Ta2lsbFJlc3BvbnNlEhEKCWlzU3VjY2VzcxgBIAEoCBIOCgZjYXJkSWQYAiABKAkiPgoYQjJDX1VzZVNraWxsTm90aWZpY2F0aW9uEiIKBXNraWxsGAEgASgLMhMuUHJvdG9jb2wuU2tpbGxEYXRhIkMKC0IyQ19BZGRDYXJkEg4KBmNhcmRJZBgBIAEoCRIkCghjYXJkRGF0YRgCIAEoCzISLlByb3RvY29sLkNhcmREYXRhIkgKEEIyR19Jbml0Q2FyZERhdGESJAoIY2FyZERhdGEYASADKAsyEi5Qcm90b2NvbC5DYXJkRGF0YRIOCgZ1c2VySWQYAiABKAkiOAoQRzJDX0luaXRDYXJkRGF0YRIkCghjYXJkRGF0YRgBIAMoCzISLlByb3RvY29sLkNhcmREYXRhYgZwcm90bzM", [file_enum, file_struct]);

/**
 * @generated from message Protocol.C2B_SkillRequest
 */
export type C2B_SkillRequest = Message<"Protocol.C2B_SkillRequest"> & {
  /**
   * @generated from field: Protocol.SkillData skill = 1;
   */
  skill?: SkillData;

  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;

  /**
   * @generated from field: string cardId = 3;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.C2B_SkillRequest.
 * Use `create(C2B_SkillRequestSchema)` to create a new message.
 */
export const C2B_SkillRequestSchema: GenMessage<C2B_SkillRequest> = /*@__PURE__*/
  messageDesc(file_skill, 0);

/**
 * 스킬 카드 사용 응답
 *
 * @generated from message Protocol.B2C_SkillResponse
 */
export type B2C_SkillResponse = Message<"Protocol.B2C_SkillResponse"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;

  /**
   * 카드 사용 요청 -> 서버로부터 응답을 받으면: 패에서 카드 제거거거
   *
   * @generated from field: string cardId = 2;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.B2C_SkillResponse.
 * Use `create(B2C_SkillResponseSchema)` to create a new message.
 */
export const B2C_SkillResponseSchema: GenMessage<B2C_SkillResponse> = /*@__PURE__*/
  messageDesc(file_skill, 1);

/**
 * 스킬 카드 사용 알림
 *
 * @generated from message Protocol.B2C_UseSkillNotification
 */
export type B2C_UseSkillNotification = Message<"Protocol.B2C_UseSkillNotification"> & {
  /**
   * @generated from field: Protocol.SkillData skill = 1;
   */
  skill?: SkillData;
};

/**
 * Describes the message Protocol.B2C_UseSkillNotification.
 * Use `create(B2C_UseSkillNotificationSchema)` to create a new message.
 */
export const B2C_UseSkillNotificationSchema: GenMessage<B2C_UseSkillNotification> = /*@__PURE__*/
  messageDesc(file_skill, 2);

/**
 * 카드 추가 알림
 *
 * @generated from message Protocol.B2C_AddCard
 */
export type B2C_AddCard = Message<"Protocol.B2C_AddCard"> & {
  /**
   * @generated from field: string cardId = 1;
   */
  cardId: string;

  /**
   * @generated from field: Protocol.CardData cardData = 2;
   */
  cardData?: CardData;
};

/**
 * Describes the message Protocol.B2C_AddCard.
 * Use `create(B2C_AddCardSchema)` to create a new message.
 */
export const B2C_AddCardSchema: GenMessage<B2C_AddCard> = /*@__PURE__*/
  messageDesc(file_skill, 3);

/**
 * 초기 카드 데이터 알림
 *
 * @generated from message Protocol.B2G_InitCardData
 */
export type B2G_InitCardData = Message<"Protocol.B2G_InitCardData"> & {
  /**
   * @generated from field: repeated Protocol.CardData cardData = 1;
   */
  cardData: CardData[];

  /**
   * @generated from field: string userId = 2;
   */
  userId: string;
};

/**
 * Describes the message Protocol.B2G_InitCardData.
 * Use `create(B2G_InitCardDataSchema)` to create a new message.
 */
export const B2G_InitCardDataSchema: GenMessage<B2G_InitCardData> = /*@__PURE__*/
  messageDesc(file_skill, 4);

/**
 * @generated from message Protocol.G2C_InitCardData
 */
export type G2C_InitCardData = Message<"Protocol.G2C_InitCardData"> & {
  /**
   * @generated from field: repeated Protocol.CardData cardData = 1;
   */
  cardData: CardData[];
};

/**
 * Describes the message Protocol.G2C_InitCardData.
 * Use `create(G2C_InitCardDataSchema)` to create a new message.
 */
export const G2C_InitCardDataSchema: GenMessage<G2C_InitCardData> = /*@__PURE__*/
  messageDesc(file_skill, 5);

