// @generated by protoc-gen-es v2.2.2 with parameter "target=js"
// @generated from file struct.proto (package Protocol, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_enum } from "./enum_pb.js";

/**
 * Describes the file struct.proto.
 */
export const file_struct = /*@__PURE__*/
  fileDesc("CgxzdHJ1Y3QucHJvdG8SCFByb3RvY29sIiUKCEJhc2VEYXRhEgoKAmhwGAEgASgFEg0KBW1heEhwGAIgASgFIlMKCVRvd2VyRGF0YRIPCgd0b3dlcklkGAEgASgFEhAKCHByZWZhYklkGAIgASgJEiMKCHRvd2VyUG9zGAMgASgLMhEuUHJvdG9jb2wuUG9zSW5mbyJtCgtNb25zdGVyRGF0YRIRCgltb25zdGVySWQYASABKAUSFQoNbW9uc3Rlck51bWJlchgCIAEoBRINCgVsZXZlbBgDIAEoBRIlCgptb25zdGVyUG9zGAQgASgLMhEuUHJvdG9jb2wuUG9zSW5mbyI2CghVc2VyRGF0YRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhAKCHByZWZhYklkGAMgASgJIpQBCghSb29tRGF0YRIKCgJpZBgBIAEoBRIPCgdvd25lcklkGAIgASgJEgwKBG5hbWUYAyABKAkSEgoKbWF4VXNlck51bRgEIAEoBRImCgVzdGF0ZRgFIAEoDjIXLlByb3RvY29sLlJvb21TdGF0ZVR5cGUSIQoFdXNlcnMYBiADKAsyEi5Qcm90b2NvbC5Vc2VyRGF0YSItCgdQb3NJbmZvEgwKBHV1aWQYASABKAkSCQoBeBgCIAEoAhIJCgF5GAMgASgCIlkKDkdhbWVQbGF5ZXJEYXRhEiMKCHBvc2l0aW9uGAEgASgLMhEuUHJvdG9jb2wuUG9zSW5mbxIQCghuaWNrbmFtZRgCIAEoCRIQCghwcmVmYWJJZBgDIAEoCSIyCglFcnJvckRhdGESFAoMcmVzcG9uc2VDb2RlGAEgASgFEg8KB21lc3NhZ2UYAiABKAkiLAoIQ2FyZERhdGESDgoGY2FyZElkGAEgASgJEhAKCHByZWZhYklkGAIgASgJYgZwcm90bzM", [file_enum]);

/**
 * Describes the message Protocol.BaseData.
 * Use `create(BaseDataSchema)` to create a new message.
 */
export const BaseDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 0);

/**
 * Describes the message Protocol.TowerData.
 * Use `create(TowerDataSchema)` to create a new message.
 */
export const TowerDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 1);

/**
 * Describes the message Protocol.MonsterData.
 * Use `create(MonsterDataSchema)` to create a new message.
 */
export const MonsterDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 2);

/**
 * Describes the message Protocol.UserData.
 * Use `create(UserDataSchema)` to create a new message.
 */
export const UserDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 3);

/**
 * Describes the message Protocol.RoomData.
 * Use `create(RoomDataSchema)` to create a new message.
 */
export const RoomDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 4);

/**
 * Describes the message Protocol.PosInfo.
 * Use `create(PosInfoSchema)` to create a new message.
 */
export const PosInfoSchema = /*@__PURE__*/
  messageDesc(file_struct, 5);

/**
 * Describes the message Protocol.GamePlayerData.
 * Use `create(GamePlayerDataSchema)` to create a new message.
 */
export const GamePlayerDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 6);

/**
 * Describes the message Protocol.ErrorData.
 * Use `create(ErrorDataSchema)` to create a new message.
 */
export const ErrorDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 7);

/**
 * Describes the message Protocol.CardData.
 * Use `create(CardDataSchema)` to create a new message.
 */
export const CardDataSchema = /*@__PURE__*/
  messageDesc(file_struct, 8);

