// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file tower.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PosInfo, TowerData } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tower.proto.
 */
export const file_tower: GenFile = /*@__PURE__*/
  fileDesc("Cgt0b3dlci5wcm90bxIIUHJvdG9jb2wibAoVQzJHX1Rvd2VyQnVpbGRSZXF1ZXN0EiIKBXRvd2VyGAEgASgLMhMuUHJvdG9jb2wuVG93ZXJEYXRhEg8KB293bmVySWQYAiABKAkSDgoGcm9vbUlkGAMgASgFEg4KBmNhcmRJZBgEIAEoCSJsChVHMkJfVG93ZXJCdWlsZFJlcXVlc3QSIgoFdG93ZXIYASABKAsyEy5Qcm90b2NvbC5Ub3dlckRhdGESDwoHb3duZXJJZBgCIAEoCRIOCgZyb29tSWQYAyABKAUSDgoGY2FyZElkGAQgASgJImEKGkIyR19Ub3dlckJ1aWxkTm90aWZpY2F0aW9uEiIKBXRvd2VyGAEgASgLMhMuUHJvdG9jb2wuVG93ZXJEYXRhEg8KB293bmVySWQYAiABKAkSDgoGcm9vbUlkGAMgASgFIlEKGkcyQ19Ub3dlckJ1aWxkTm90aWZpY2F0aW9uEiIKBXRvd2VyGAEgASgLMhMuUHJvdG9jb2wuVG93ZXJEYXRhEg8KB293bmVySWQYAiABKAkigAEKIkIyR19Ub3dlckF0dGFja01vbnN0ZXJOb3RpZmljYXRpb24SDwoHdG93ZXJJZBgBIAEoCRIlCgptb25zdGVyUG9zGAIgASgLMhEuUHJvdG9jb2wuUG9zSW5mbxISCgp0cmF2ZWxUaW1lGAMgASgCEg4KBnJvb21JZBgEIAEoBSJwCiJHMkNfVG93ZXJBdHRhY2tNb25zdGVyTm90aWZpY2F0aW9uEg8KB3Rvd2VySWQYASABKAkSJQoKbW9uc3RlclBvcxgCIAEoCzIRLlByb3RvY29sLlBvc0luZm8SEgoKdHJhdmVsVGltZRgDIAEoAiJSChxCMkdfVG93ZXJEZXN0cm95Tm90aWZpY2F0aW9uEhEKCWlzU3VjY2VzcxgBIAEoCBIPCgd0b3dlcklkGAIgASgJEg4KBnJvb21JZBgDIAEoBSJCChxHMkNfVG93ZXJEZXN0cm95Tm90aWZpY2F0aW9uEhEKCWlzU3VjY2VzcxgBIAEoCBIPCgd0b3dlcklkGAIgASgJIkIKG0IyR19CYXNlRGVzdHJveU5vdGlmaWNhdGlvbhITCgtpc0Rlc3Ryb2llZBgBIAEoCBIOCgZyb29tSWQYAiABKAUiMgobRzJDX0Jhc2VEZXN0cm95Tm90aWZpY2F0aW9uEhMKC2lzRGVzdHJvaWVkGAEgASgIIl8KIUIyR19Ub3dlckhlYWx0aFVwZGF0ZU5vdGlmaWNhdGlvbhIPCgd0b3dlcklkGAEgASgJEgoKAmhwGAIgASgFEg0KBW1heEhwGAMgASgFEg4KBnJvb21JZBgEIAEoBSJPCiFHMkNfVG93ZXJIZWFsdGhVcGRhdGVOb3RpZmljYXRpb24SDwoHdG93ZXJJZBgBIAEoCRIKCgJocBgCIAEoBRINCgVtYXhIcBgDIAEoBSJgChlCMkdfVG93ZXJCdWZmTm90aWZpY2F0aW9uEg8KB3Rvd2VySWQYASADKAkSEAoIYnVmZlR5cGUYAiABKAkSEAoIaXNCdWZmZWQYAyABKAgSDgoGcm9vbUlkGAQgASgFIlAKGUcyQ19Ub3dlckJ1ZmZOb3RpZmljYXRpb24SDwoHdG93ZXJJZBgBIAMoCRIQCghidWZmVHlwZRgCIAEoCRIQCghpc0J1ZmZlZBgDIAEoCGIGcHJvdG8z", [file_struct]);

/**
 * C->G 타워 생성 요청
 *
 * @generated from message Protocol.C2G_TowerBuildRequest
 */
export type C2G_TowerBuildRequest = Message<"Protocol.C2G_TowerBuildRequest"> & {
  /**
   * 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 유저 ID
   *
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;

  /**
   * 룸 ID
   *
   * @generated from field: int32 roomId = 3;
   */
  roomId: number;

  /**
   * @generated from field: string cardId = 4;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.C2G_TowerBuildRequest.
 * Use `create(C2G_TowerBuildRequestSchema)` to create a new message.
 */
export const C2G_TowerBuildRequestSchema: GenMessage<C2G_TowerBuildRequest> = /*@__PURE__*/
  messageDesc(file_tower, 0);

/**
 * G->B 타워 생성 요청청
 *
 * @generated from message Protocol.G2B_TowerBuildRequest
 */
export type G2B_TowerBuildRequest = Message<"Protocol.G2B_TowerBuildRequest"> & {
  /**
   * 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 타워 정보
   *
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;

  /**
   * 타워 정보
   *
   * @generated from field: int32 roomId = 3;
   */
  roomId: number;

  /**
   * @generated from field: string cardId = 4;
   */
  cardId: string;
};

/**
 * Describes the message Protocol.G2B_TowerBuildRequest.
 * Use `create(G2B_TowerBuildRequestSchema)` to create a new message.
 */
export const G2B_TowerBuildRequestSchema: GenMessage<G2B_TowerBuildRequest> = /*@__PURE__*/
  messageDesc(file_tower, 1);

/**
 * 타워 생성 알림
 *
 * @generated from message Protocol.B2G_TowerBuildNotification
 */
export type B2G_TowerBuildNotification = Message<"Protocol.B2G_TowerBuildNotification"> & {
  /**
   * 생성된 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 타워 생성자 ID
   *
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;

  /**
   * @generated from field: int32 roomId = 3;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.B2G_TowerBuildNotification.
 * Use `create(B2G_TowerBuildNotificationSchema)` to create a new message.
 */
export const B2G_TowerBuildNotificationSchema: GenMessage<B2G_TowerBuildNotification> = /*@__PURE__*/
  messageDesc(file_tower, 2);

/**
 * @generated from message Protocol.G2C_TowerBuildNotification
 */
export type G2C_TowerBuildNotification = Message<"Protocol.G2C_TowerBuildNotification"> & {
  /**
   * 생성된 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 타워 생성자 ID
   *
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;
};

/**
 * Describes the message Protocol.G2C_TowerBuildNotification.
 * Use `create(G2C_TowerBuildNotificationSchema)` to create a new message.
 */
export const G2C_TowerBuildNotificationSchema: GenMessage<G2C_TowerBuildNotification> = /*@__PURE__*/
  messageDesc(file_tower, 3);

/**
 * 타워 -> 몬스터 공격 알림
 *
 * @generated from message Protocol.B2G_TowerAttackMonsterNotification
 */
export type B2G_TowerAttackMonsterNotification = Message<"Protocol.B2G_TowerAttackMonsterNotification"> & {
  /**
   * @generated from field: string towerId = 1;
   */
  towerId: string;

  /**
   * @generated from field: Protocol.PosInfo monsterPos = 2;
   */
  monsterPos?: PosInfo;

  /**
   * @generated from field: float travelTime = 3;
   */
  travelTime: number;

  /**
   * @generated from field: int32 roomId = 4;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.B2G_TowerAttackMonsterNotification.
 * Use `create(B2G_TowerAttackMonsterNotificationSchema)` to create a new message.
 */
export const B2G_TowerAttackMonsterNotificationSchema: GenMessage<B2G_TowerAttackMonsterNotification> = /*@__PURE__*/
  messageDesc(file_tower, 4);

/**
 * 타워 -> 몬스터 공격 알림
 *
 * @generated from message Protocol.G2C_TowerAttackMonsterNotification
 */
export type G2C_TowerAttackMonsterNotification = Message<"Protocol.G2C_TowerAttackMonsterNotification"> & {
  /**
   * @generated from field: string towerId = 1;
   */
  towerId: string;

  /**
   * @generated from field: Protocol.PosInfo monsterPos = 2;
   */
  monsterPos?: PosInfo;

  /**
   * @generated from field: float travelTime = 3;
   */
  travelTime: number;
};

/**
 * Describes the message Protocol.G2C_TowerAttackMonsterNotification.
 * Use `create(G2C_TowerAttackMonsterNotificationSchema)` to create a new message.
 */
export const G2C_TowerAttackMonsterNotificationSchema: GenMessage<G2C_TowerAttackMonsterNotification> = /*@__PURE__*/
  messageDesc(file_tower, 5);

/**
 * 타워 파괴 알림
 *
 * @generated from message Protocol.B2G_TowerDestroyNotification
 */
export type B2G_TowerDestroyNotification = Message<"Protocol.B2G_TowerDestroyNotification"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;

  /**
   * @generated from field: string towerId = 2;
   */
  towerId: string;

  /**
   * @generated from field: int32 roomId = 3;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.B2G_TowerDestroyNotification.
 * Use `create(B2G_TowerDestroyNotificationSchema)` to create a new message.
 */
export const B2G_TowerDestroyNotificationSchema: GenMessage<B2G_TowerDestroyNotification> = /*@__PURE__*/
  messageDesc(file_tower, 6);

/**
 * 타워 파괴 알림
 *
 * @generated from message Protocol.G2C_TowerDestroyNotification
 */
export type G2C_TowerDestroyNotification = Message<"Protocol.G2C_TowerDestroyNotification"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;

  /**
   * @generated from field: string towerId = 2;
   */
  towerId: string;
};

/**
 * Describes the message Protocol.G2C_TowerDestroyNotification.
 * Use `create(G2C_TowerDestroyNotificationSchema)` to create a new message.
 */
export const G2C_TowerDestroyNotificationSchema: GenMessage<G2C_TowerDestroyNotification> = /*@__PURE__*/
  messageDesc(file_tower, 7);

/**
 * 베이스 파괴 알림
 *
 * @generated from message Protocol.B2G_BaseDestroyNotification
 */
export type B2G_BaseDestroyNotification = Message<"Protocol.B2G_BaseDestroyNotification"> & {
  /**
   * @generated from field: bool isDestroied = 1;
   */
  isDestroied: boolean;

  /**
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.B2G_BaseDestroyNotification.
 * Use `create(B2G_BaseDestroyNotificationSchema)` to create a new message.
 */
export const B2G_BaseDestroyNotificationSchema: GenMessage<B2G_BaseDestroyNotification> = /*@__PURE__*/
  messageDesc(file_tower, 8);

/**
 * 베이스 파괴 알림
 *
 * @generated from message Protocol.G2C_BaseDestroyNotification
 */
export type G2C_BaseDestroyNotification = Message<"Protocol.G2C_BaseDestroyNotification"> & {
  /**
   * @generated from field: bool isDestroied = 1;
   */
  isDestroied: boolean;
};

/**
 * Describes the message Protocol.G2C_BaseDestroyNotification.
 * Use `create(G2C_BaseDestroyNotificationSchema)` to create a new message.
 */
export const G2C_BaseDestroyNotificationSchema: GenMessage<G2C_BaseDestroyNotification> = /*@__PURE__*/
  messageDesc(file_tower, 9);

/**
 * 타워 체력 업데이트 알림
 *
 * @generated from message Protocol.B2G_TowerHealthUpdateNotification
 */
export type B2G_TowerHealthUpdateNotification = Message<"Protocol.B2G_TowerHealthUpdateNotification"> & {
  /**
   * @generated from field: string towerId = 1;
   */
  towerId: string;

  /**
   * @generated from field: int32 hp = 2;
   */
  hp: number;

  /**
   * @generated from field: int32 maxHp = 3;
   */
  maxHp: number;

  /**
   * @generated from field: int32 roomId = 4;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.B2G_TowerHealthUpdateNotification.
 * Use `create(B2G_TowerHealthUpdateNotificationSchema)` to create a new message.
 */
export const B2G_TowerHealthUpdateNotificationSchema: GenMessage<B2G_TowerHealthUpdateNotification> = /*@__PURE__*/
  messageDesc(file_tower, 10);

/**
 * 타워 체력 업데이트 알림
 *
 * @generated from message Protocol.G2C_TowerHealthUpdateNotification
 */
export type G2C_TowerHealthUpdateNotification = Message<"Protocol.G2C_TowerHealthUpdateNotification"> & {
  /**
   * @generated from field: string towerId = 1;
   */
  towerId: string;

  /**
   * @generated from field: int32 hp = 2;
   */
  hp: number;

  /**
   * @generated from field: int32 maxHp = 3;
   */
  maxHp: number;
};

/**
 * Describes the message Protocol.G2C_TowerHealthUpdateNotification.
 * Use `create(G2C_TowerHealthUpdateNotificationSchema)` to create a new message.
 */
export const G2C_TowerHealthUpdateNotificationSchema: GenMessage<G2C_TowerHealthUpdateNotification> = /*@__PURE__*/
  messageDesc(file_tower, 11);

/**
 * 타워 버프 상태 알림
 *
 * @generated from message Protocol.B2G_TowerBuffNotification
 */
export type B2G_TowerBuffNotification = Message<"Protocol.B2G_TowerBuffNotification"> & {
  /**
   * 버프 받은/해제된 타워 ID
   *
   * @generated from field: repeated string towerId = 1;
   */
  towerId: string[];

  /**
   * @generated from field: string buffType = 2;
   */
  buffType: string;

  /**
   * true: 버프 적용, false: 버프 해제
   *
   * @generated from field: bool isBuffed = 3;
   */
  isBuffed: boolean;

  /**
   * @generated from field: int32 roomId = 4;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.B2G_TowerBuffNotification.
 * Use `create(B2G_TowerBuffNotificationSchema)` to create a new message.
 */
export const B2G_TowerBuffNotificationSchema: GenMessage<B2G_TowerBuffNotification> = /*@__PURE__*/
  messageDesc(file_tower, 12);

/**
 * 타워 버프 상태 알림
 *
 * @generated from message Protocol.G2C_TowerBuffNotification
 */
export type G2C_TowerBuffNotification = Message<"Protocol.G2C_TowerBuffNotification"> & {
  /**
   * 버프 받은/해제된 타워 ID
   *
   * @generated from field: repeated string towerId = 1;
   */
  towerId: string[];

  /**
   * @generated from field: string buffType = 2;
   */
  buffType: string;

  /**
   * true: 버프 적용, false: 버프 해제
   *
   * @generated from field: bool isBuffed = 3;
   */
  isBuffed: boolean;
};

/**
 * Describes the message Protocol.G2C_TowerBuffNotification.
 * Use `create(G2C_TowerBuffNotificationSchema)` to create a new message.
 */
export const G2C_TowerBuffNotificationSchema: GenMessage<G2C_TowerBuffNotification> = /*@__PURE__*/
  messageDesc(file_tower, 13);

