"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REDIS_URL = exports.DB_NAME = exports.DB_PASSWORD = exports.DB_USER = exports.DB_PORT = exports.DB_HOST = exports.CLIENT_VERSION = exports.HOST = exports.PORT = void 0;
dotenv.config();
exports.PORT = process.env.PORT || 3000;
exports.HOST = process.env.HOST || '0.0.0.0';
exports.CLIENT_VERSION = process.env.CLIENT_VERSION || '1.0.0';
exports.DB_HOST = process.env.DB_HOST || '';
exports.DB_PORT = process.env.DB_PORT || 3306;
exports.DB_USER = process.env.DB_USER || 'root';
exports.DB_PASSWORD = process.env.DB_PASSWORD || 'jkl123123';
exports.DB_NAME = process.env.DB_NAME || 'USER_DB';
exports.REDIS_URL = process.env.REDIS_URL;
